#!/usr/bin/env bash
# Script that displays numbers from 1 to 100

i=1
while ((i<101)) 
do
    if [[ $i%3 -eq 0 && $i%5 -eq 0 ]]
    then
        echo "FizzBuzz"
    elif [[ $i%3 -eq 0 ]]
    then
        echo "Fizz"
    elif [[ $i%5 -eq 0 ]]
    then
        echo "Buzz"
    else
        echo "$i"
    fi
    ((i++))
done
