#!/usr/bin/env bash
# Script that displays "Best School" 10 times but display Hi on 9th iteration

i=1
while ((i<=10)) 
do
    if [ $i -eq 9 ]
    then
        echo "Hi"
    else
        echo "Best School"
    fi
    ((i++))
done
