#!/usr/bin/env bash
# Configure web-01 so that its firewall redirects port 8080/TCP to port 80/TCP.

sudo ufw default allow outgoing
sudo ufw default deny incoming
sudo ufw allow ssh
# sudo ufw limit ssh
sudo ufw allow 80/tcp
sudo ufw allow 8080/tcp
sudo ufw allow 443/tcp
CONF='*nat\n:PREROUTING ACCEPT [0:0]\n-A PREROUTING -p tcp --dport 8080 -j REDIRECT --to-port 80\nCOMMIT\n'
sed -i "11 a $CONF" /etc/ufw/before.rules
sudo ufw enable
sudo ufw reload
